@url=http://localhost:8000/api/v1/users/
@link=/api/v1/users/

@admin=/api/v1/admin/

### GET Request
GET {{url}}





## Admin book inserting
### POST add book
POST {{admin}}addbook
Content-Type: application/json

[
{
      "_id": "64f1a2b3c4d5e6f7a8b9c0d1",
      "title": "The Hobbit",
      "author": "J.R.R. Tolkien",
      "imgURL": "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
      "isbn": "9780547928227",
      "genre": "Fantasy",
      "availability": true,
      "averageRating": 4.7,
    },
    {
      "_id": "64f1a2b3c4d5e6f7a8b9c0d2",
      "title": "1984",
      "author": "George Orwell",
      "imgURL": "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
      "isbn": "9780451524935",
      "genre": "Dystopian",
      "availability": false,
      "averageRating": 4.6,
    },
]