@url=http://localhost:8000
@link=/api/v1/users/

@admin=/api/v1/admin/
@auth=/api/v1/auth/

### GET request to server only, not router
GET {{url}}


## Admin book inserting
### POST add book
POST {{url}}{{admin}}addbook
Content-Type: application/json

[
{
      "title": "The Hobbit",
      "author": "J.R.R. Tolkien",
      "imgURL": "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
      "isbn": "9780547928227",
      "genre": "Fantasy",
      "availability": true,
      "averageRating": 4.7
    },
    {
      "title": "1984",
      "author": "George Orwell",
      "imgURL": "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
      "isbn": "9780451524935",
      "genre": "Dystopian",
      "availability": false,
      "averageRating": 4.6
    }
]

### GET data from all book
GET {{url}}{{admin}}book

### GET data from by id
GET {{url}}{{admin}}book?_id=6ab3d03c66e422e88e5a7aab
Content-Type: application/json

  


### Delete book
DELETE {{url}}{{admin}}
Content-Type: application/json

 [
  "6ab3cb0166e422e88e5a7aa7"  
 ]
### Update  book
patch {{url}}{{admin}}
Content-Type: application/json

 {
"_id":"6ab66b0e3db9813f98e1339d",
  "title": "Moby Yadin",
  "author": "Herman Melville",
  "imgURL": "https://covers.openlibrary.org/b/isbn/9781503280786-L.jpg",
  "isbn": "9781503280786",
  "genre": "Classic"
 }


### AUTH API

### post new user
POST {{url}}{{auth}}register
Content-Type: application/json

{
    "fName":"Yadin",
    "lName":"Nou",
    "email":"nouyadin@hotmail.com",
    "phone":"043333",
    "password":"123"
}
### post to activate user
POST {{url}}{{auth}}activate-user
Content-Type: application/json

{
    "sessionId":"6ac3960ba4bcd9f9e6fd0162",
    "t":"ce429e48-1f04-493d-a4bd-28b200de7bcc"
}
  

### Login user
POST {{url}}{{auth}}login
Content-Type: application/json

{
    "email":"nouyadin007@gmail.com",
    "password":"123"
}
 
### GET Request user profile
GET {{url}}{{link}}profile
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vdXlhZGluMDA3QGdtYWlsLmNvbSIsImlhdCI6MTc5MTM4Mzk1NywiZXhwIjoxNzkxMzg0ODU3fQ.kMXDyJ3REz4eY-Dj5PSlMoiWOHfhCLYQQSTbyJ7UWVs
