@url=http://localhost:8000
@link=/api/v1/users/

@admin=/api/v1/admin/
@auth=/api/v1/auth/
### GET Request
GET {{url}}{{link}}


### GET request to server only, not router
GET {{url}}


## Admin book inserting
### POST add book
POST {{url}}{{admin}}addbook
Content-Type: application/json

[
{
      "title": "The Hobbit",
      "author": "J.R.R. Tolkien",
      "imgURL": "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
      "isbn": "9780547928227",
      "genre": "Fantasy",
      "availability": true,
      "averageRating": 4.7
    },
    {
      "title": "1984",
      "author": "George Orwell",
      "imgURL": "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
      "isbn": "9780451524935",
      "genre": "Dystopian",
      "availability": false,
      "averageRating": 4.6
    }
]

### GET data from all book
GET {{url}}{{admin}}book

### GET data from by id
GET {{url}}{{admin}}book?_id=6ab3d03c66e422e88e5a7aab
Content-Type: application/json

  


### Delete book
DELETE {{url}}{{admin}}
Content-Type: application/json

 [
  "6ab3cb0166e422e88e5a7aa7"  
 ]


### AUTH API

### post new user
POST {{url}}{{auth}}register
Content-Type: application/json

{
    "fName":"Yadin",
    "lName":"Nou",
    "email":"nouyadin@gmail.com",
    "phone":"043333",
    "password":"123"
}
 